name: Static Security Pipeline

on:
  pull_request:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  security-events: write

jobs:
  sast:
    uses: paulocesarmsf/appsec-academy/.github/workflows/static-security-pipeline.yml@main
